import { Size } from '@ohos/hypium'

export const PADDING_TITLE: Padding = {
  top: 20,
  left: 20,
  right: 20,
  bottom: 20
}
export const PADDING_SUBTITLE: Padding = {
  top: 20,
  left: 20,
  right: 20,
  bottom: 0
}

export const IMAGE_TITLE_SIZE: SizeOptions = {
  width: 30,
  height: 30
}

export const FONT_SIZE_TITLE: number = 20
export const FONT_SIZE_SUB_TITLE: number = 16
export const FONT_SIZE_BODY: number = 12